import { AssessmentData } from './graderTypes';
import { sampleBiologyOcrResult, sampleMathsOcrResult } from './ocrService';

export const sampleBiologyAssessment: AssessmentData = {
  id: 'bio-unit-test-10',
  title: 'Class 10 Biology Unit Test',
  subject: 'Biology & Life Processes',
  grade: 'Class 10th - Section B',
  studentName: 'Aarav Sharma',
  rollNumber: 'DPS-10B-24',
  school: 'Delhi Public School, Bokaro Steel City',
  date: 'August 24, 2026',
  totalMarksAwarded: 40,
  maxTotalMarks: 48,
  ocrResult: sampleBiologyOcrResult,
  questionPaperFile: {
    name: 'Class_10_biology_unit_test.pdf',
    size: '2MB',
    pages: 2,
  },
  answerSheetFile: {
    name: 'student_1_answer_sheet.pdf',
    size: '8MB',
    pages: 4,
  },
  pages: [
    { pageNumber: 1, title: 'Page 1 - Photosynthesis & Cell Organelles' },
    { pageNumber: 2, title: 'Page 2 - Human Heart & Respiration' },
    { pageNumber: 3, title: 'Page 3 - Excretory System & Plant Physiology' },
    { pageNumber: 4, title: 'Page 4 - Light Experiments & Pulmonary Volumes' },
  ],
  unmatchedAnswers: [
    {
      id: 'unmatched-1',
      label: 'Extra Rough Note / Unmatched Working',
      page: 4,
      topPercent: 82,
      leftPercent: 12,
      widthPercent: 82,
      heightPercent: 14,
      extractedText: 'Rough note: Rate of photosynthesis decreases when temperature exceeds 40°C due to enzyme denaturation.',
      aiNote: 'Student wrote an additional explanatory note on thermal enzyme denaturation that does not correspond directly to any numbered question on the paper.',
    },
  ],
  questions: [
    {
      id: 'q1',
      number: '1',
      mainNumber: '1',
      text: 'Which blood vessel carries blood away from the heart?',
      maxMarks: 2,
      marksAwarded: 2,
      status: 'answered',
      section: 'Section A',
      questionType: 'short',
      aiFeedback: 'Accurate and concise! You correctly identified arteries (specifically the aorta and pulmonary artery) as carrying blood away from the heart under high pressure.',
      suggestedSolution: 'Arteries carry blood away from the heart to various organs.',
      studentAnswerText: 'Q1. Arteries are the thick-walled blood vessels that carry blood away from the heart under high pressure to different parts of the body.',
      orderInAnswerSheet: 1,
      isOutOfOrder: false,
      keyConcepts: ['Arteries', 'Away from heart', 'High pressure'],
      criteriaBreakdown: [
        { criterion: 'Identification of Arteries', marks: 1, maxMarks: 1 },
        { criterion: 'Direction of blood flow explanation', marks: 1, maxMarks: 1 },
      ],
      answerRegion: {
        page: 1,
        topPercent: 5,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 32,
        label: 'Q1',
      },
    },
    {
      id: 'q2',
      number: '2',
      mainNumber: '2',
      text: 'Which of the following organelles is primarily involved in photosynthesis?',
      maxMarks: 2,
      marksAwarded: 2,
      status: 'answered',
      section: 'Section A',
      questionType: 'short',
      aiFeedback: 'Excellent work! You correctly identified the chloroplast as the organelle responsible for photosynthesis. Keep it up!',
      suggestedSolution: 'Chloroplasts contain chlorophyll pigments and thylakoid membranes where light and dark reactions occur.',
      studentAnswerText: 'Q2. The process mainly occurs in the chloroplast of the plant cell. It has two main stages: 1. Light reaction - Captures light energy. 2. Dark reaction - Uses energy to make glucose.',
      orderInAnswerSheet: 2,
      isOutOfOrder: false,
      keyConcepts: ['Chloroplast', 'Chlorophyll', 'Light & Dark reactions'],
      criteriaBreakdown: [
        { criterion: 'Naming Chloroplast', marks: 1, maxMarks: 1 },
        { criterion: 'Stating light/dark stage roles', marks: 1, maxMarks: 1 },
      ],
      answerRegion: {
        page: 1,
        topPercent: 42,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 15,
        label: 'Q2',
      },
    },
    {
      id: 'q3',
      number: '3',
      mainNumber: '3',
      text: 'Explain the role of chloroplasts in photosynthesis, naming the main pigments involved and briefly outlining the two major stages of the process.',
      maxMarks: 2,
      marksAwarded: 2,
      status: 'answered',
      section: 'Section A',
      questionType: 'long',
      aiFeedback: 'Thorough explanation with both biochemical stages accurately identified alongside chlorophyll a, b and carotenoids.',
      suggestedSolution: 'Chloroplasts trap solar radiation via chlorophyll and convert it into chemical energy through light-dependent photolysis and light-independent carbon fixation.',
      studentAnswerText: 'Q3. Chloroplasts contain chlorophyll pigments (chlorophyll a and b) in thylakoid grana. Light reactions produce ATP & NADPH; Stroma carries out Calvin cycle for glucose synthesis.',
      orderInAnswerSheet: 3,
      isOutOfOrder: false,
      keyConcepts: ['Thylakoids', 'Stroma', 'Calvin cycle', 'ATP & NADPH'],
      criteriaBreakdown: [
        { criterion: 'Pigments naming', marks: 1, maxMarks: 1 },
        { criterion: 'Stage description', marks: 1, maxMarks: 1 },
      ],
      answerRegion: {
        page: 1,
        topPercent: 60,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 28,
        label: 'Q3',
      },
    },
    {
      id: 'q4',
      number: '4',
      mainNumber: '4',
      text: 'Describe the flow of blood through the human heart starting from the right atrium and ending at the aorta; include the names of valves crossed.',
      maxMarks: 2,
      marksAwarded: 0,
      status: 'unanswered',
      section: 'Section A',
      questionType: 'long',
      aiFeedback: 'Question not attempted by student. Expected pathway: Right Atrium -> Tricuspid Valve -> Right Ventricle -> Pulmonary Valve -> Lungs -> Left Atrium -> Bicuspid Valve -> Left Ventricle -> Aortic Valve -> Aorta.',
      suggestedSolution: 'Right atrium -> Tricuspid valve -> Right ventricle -> Pulmonary semilunar valve -> Pulmonary artery -> Lungs -> Pulmonary veins -> Left atrium -> Bicuspid (mitral) valve -> Left ventricle -> Aortic valve -> Aorta.',
      orderInAnswerSheet: undefined,
      isOutOfOrder: false,
      keyConcepts: ['Tricuspid valve', 'Bicuspid valve', 'Semilunar valves', 'Systemic circulation'],
      criteriaBreakdown: [
        { criterion: 'Correct cardiac chamber sequence', marks: 0, maxMarks: 1 },
        { criterion: 'Identification of 4 valves', marks: 0, maxMarks: 1 },
      ],
    },
    {
      id: 'q5',
      number: '5',
      mainNumber: '5',
      text: 'Draw a labelled diagram of an alveolus showing capillaries and air space (label alveolar sac, capillary, and direction of gas exchange).',
      maxMarks: 2,
      marksAwarded: 2,
      status: 'answered',
      section: 'Section A',
      questionType: 'diagram',
      aiFeedback: 'Neat hand-drawn sketch with all required annotations including alveolar wall, blood capillary, O2 inward diffusion, and CO2 outward diffusion.',
      suggestedSolution: 'Diagram should indicate thin squamous epithelium, blood capillary lumen, red blood cells, and gas partial pressure diffusion arrows.',
      studentAnswerText: '[Handwritten Sketch & Labels]: Alveolar air sac, capillary endothelium, O2 diffusion into RBC, CO2 diffusing out into alveolus.',
      orderInAnswerSheet: 4,
      isOutOfOrder: false,
      keyConcepts: ['Diffusion gradient', 'Capillary membrane', 'Surfactant lining'],
      criteriaBreakdown: [
        { criterion: 'Diagram accuracy', marks: 1, maxMarks: 1 },
        { criterion: 'Labeling & Gas direction', marks: 1, maxMarks: 1 },
      ],
      answerRegion: {
        page: 2,
        topPercent: 6,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 26,
        label: 'Q5',
      },
    },
    {
      id: 'q6',
      number: '6',
      mainNumber: '6',
      text: 'Draw a neat labelled diagram of the human digestive system (stomach, small intestine, large intestine, liver, pancreas) and label the site where most absorption occurs.',
      maxMarks: 5,
      marksAwarded: 4,
      status: 'partial',
      section: 'Section A',
      questionType: 'diagram',
      aiFeedback: 'Well-drawn anatomical diagram with 5/5 organs correctly located. Note: Answer spans across Page 2 (Organ Diagram) and Page 3 (Absorption & Villi Details). Minor omission: Did not detail lacteal lymph absorption.',
      suggestedSolution: 'Alimentary canal showing esophagus, stomach (C-shaped), duodenum, liver with gall bladder, pancreas under stomach, and ileum marked as the primary site of nutrient absorption.',
      studentAnswerText: '[Diagram with labels]: Stomach, Liver, Pancreas, Small Intestine (Ileum marked as maximum absorption site), Large Intestine (Colon/Rectum). Continued on Page 3 with absorption mechanism details.',
      orderInAnswerSheet: 5,
      isOutOfOrder: false,
      keyConcepts: ['Small intestine', 'Villi absorption', 'Pancreatic enzymes'],
      criteriaBreakdown: [
        { criterion: 'Organ placement & proportion (Page 2)', marks: 2, maxMarks: 2 },
        { criterion: 'All 5 organ labels (Page 2)', marks: 2, maxMarks: 2 },
        { criterion: 'Absorption site magnification & mechanism (Page 3)', marks: 0, maxMarks: 1 },
      ],
      answerRegion: {
        page: 2,
        topPercent: 35,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 30,
        label: 'Q6 (Part 1: Organ Diagram)',
        spansMultiplePages: true,
        continuationNote: 'Diagram on Page 2 • Ileum Villi & Absorption Mechanism on Page 3',
        additionalRegions: [
          {
            page: 3,
            topPercent: 4,
            leftPercent: 12,
            widthPercent: 82,
            heightPercent: 14,
            label: 'Q6 (Part 2: Villi Absorption)',
            segmentTitle: 'Part 2: Ileum Microvilli Nutrient Absorption',
          },
        ],
      },
    },
    {
      id: 'q7',
      number: '7',
      mainNumber: '7',
      text: 'Describe the structure of a nephron and explain how glomerular filtration and selective reabsorption occur in the renal tubule.',
      maxMarks: 5,
      marksAwarded: 5,
      status: 'answered',
      section: 'Section A',
      questionType: 'long',
      aiFeedback: 'Outstanding! The nephron structure is precisely illustrated with ultrafiltration and selective reabsorption zones clearly designated.',
      suggestedSolution: 'Complete diagram of renal unit: Glomerular capillary network, Bowman’s cup, PCT, descending/ascending Henle loop, DCT, and Collecting Duct.',
      studentAnswerText: '[Nephron diagram]: Afferent/Efferent arterioles, Glomerular tuft, Bowman capsule, Proximal Convoluted Tubule, Henle loop, Distal Tubule, Collecting Duct.',
      orderInAnswerSheet: 6,
      isOutOfOrder: false,
      keyConcepts: ['Ultrafiltration', 'Henle Loop', 'Collecting duct'],
      criteriaBreakdown: [
        { criterion: 'Malpighian body representation', marks: 2, maxMarks: 2 },
        { criterion: 'Tubular system labels', marks: 2, maxMarks: 2 },
        { criterion: 'Flow direction arrows', marks: 1, maxMarks: 1 },
      ],
      answerRegion: {
        page: 2,
        topPercent: 68,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 28,
        label: 'Q7',
      },
    },
    {
      id: 'q8',
      number: '8',
      mainNumber: '8',
      text: 'Explain the structural differences between palisade mesophyll and spongy mesophyll and state how each structure aids its function in the leaf.',
      maxMarks: 5,
      marksAwarded: 3,
      status: 'partial',
      section: 'Section B',
      questionType: 'short',
      aiFeedback: 'Good comparison of cell orientation and chloroplast density. However, missed mentioning large air spaces in spongy mesophyll facilitating rapid gas diffusion during transpiration.',
      suggestedSolution: 'Palisade: Columnar, tightly packed, high chloroplast count for maximal light absorption. Spongy: Loosely packed, irregular shapes, large intercellular spaces for gaseous exchange.',
      studentAnswerText: 'Q8. Palisade mesophyll cells are long, columnar and packed with chloroplasts near upper epidermis for light capture. Spongy cells are loosely arranged below with air spaces.',
      orderInAnswerSheet: 7,
      isOutOfOrder: false,
      keyConcepts: ['Columnar cells', 'Intercellular spaces', 'Gas diffusion'],
      criteriaBreakdown: [
        { criterion: 'Palisade morphology & function', marks: 2, maxMarks: 2 },
        { criterion: 'Spongy morphology & function', marks: 1, maxMarks: 3 },
      ],
      answerRegion: {
        page: 3,
        topPercent: 20,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 22,
        label: 'Q8',
      },
    },
    {
      id: 'q9',
      number: '9',
      mainNumber: '9',
      text: 'What is transpiration? State two environmental factors that increase the rate of transpiration in terrestrial plants.',
      maxMarks: 5,
      marksAwarded: 5,
      status: 'answered',
      section: 'Section B',
      questionType: 'short',
      aiFeedback: 'Perfect answer. Transpiration defined as evaporative water loss through stomata, with temperature and wind velocity correctly identified as positive rate enhancers.',
      suggestedSolution: 'Transpiration is the evaporative loss of water vapor from aerial parts (primarily stomata). High temperature and increased wind speed elevate the transpiration pull.',
      studentAnswerText: 'Q9. Transpiration is the loss of water in the form of water vapor from the stomata of leaves. Factors that increase it: 1. Higher temperature 2. Increased wind speed.',
      orderInAnswerSheet: 8,
      isOutOfOrder: false,
      keyConcepts: ['Stomatal evaporation', 'Transpiration pull', 'Wind & temperature'],
      criteriaBreakdown: [
        { criterion: 'Definition of transpiration', marks: 2, maxMarks: 2 },
        { criterion: 'Two environmental factors', marks: 3, maxMarks: 3 },
      ],
      answerRegion: {
        page: 3,
        topPercent: 44,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 22,
        label: 'Q9',
      },
    },
    {
      id: 'q10',
      number: '10',
      mainNumber: '10',
      text: 'Explain how the structure of xylem vessels facilitates water transport in plants (mention one structural feature and its role).',
      maxMarks: 5,
      marksAwarded: 4,
      status: 'partial',
      section: 'Section B',
      questionType: 'long',
      aiFeedback: 'Accurately noted hollow dead cells with lignified walls providing mechanical strength. Answer spans from Page 3 into Page 4 (Summary of capillary tension).',
      suggestedSolution: 'Xylem vessels are made of dead cells joined end-to-end forming continuous hollow capillary tubes with thick lignified walls to withstand tension during ascent of sap.',
      studentAnswerText: 'Q10. Xylem vessels consist of hollow, non-living tubular cells with thick lignin walls. This allows unbroken water columns to rise by capillary action without collapse.',
      orderInAnswerSheet: 9,
      isOutOfOrder: false,
      keyConcepts: ['Lignification', 'Continuous lumen', 'Capillary action'],
      criteriaBreakdown: [
        { criterion: 'Hollow tube structure', marks: 2, maxMarks: 2 },
        { criterion: 'Lignified wall function', marks: 2, maxMarks: 3 },
      ],
      answerRegion: {
        page: 3,
        topPercent: 68,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 26,
        label: 'Q10 (Part 1: Lignified Vessels)',
        spansMultiplePages: true,
        continuationNote: 'Vessel Structure on Page 3 • Capillary Tension Summary on Page 4',
        additionalRegions: [
          {
            page: 4,
            topPercent: 4,
            leftPercent: 12,
            widthPercent: 82,
            heightPercent: 10,
            label: 'Q10 (Part 2: Tension Mechanism)',
            segmentTitle: 'Part 2: Negative Hydrostatic Pressure',
          },
        ],
      },
    },
    {
      id: 'q11a',
      number: '11 (a)',
      mainNumber: '11',
      subPart: 'a',
      text: 'A diagram shows two potted plants — Plant A in bright light with broad green leaves, Plant B kept in dim light with pale, elongated leaves. Explain why Plant B has pale and elongated leaves (etiolation).',
      maxMarks: 2,
      marksAwarded: 2,
      status: 'answered',
      section: 'Section C',
      questionType: 'short',
      aiFeedback: 'Spot on! Correctly identified etiolation and auxin concentration causing stem elongation in search of light alongside chlorophyll deficiency.',
      suggestedSolution: 'Plant B undergoes etiolation: lack of sunlight prevents chlorophyll synthesis (causing pale yellow leaves) while auxin redistribution induces rapid internodal elongation toward light.',
      studentAnswerText: 'Q11 (a). Plant B shows etiolation. Due to dim light, chlorophyll is not synthesized efficiently causing yellowing/paleness, and auxins trigger rapid stem elongation seeking light.',
      orderInAnswerSheet: 10,
      isOutOfOrder: false,
      keyConcepts: ['Etiolation', 'Auxin elongation', 'Chlorophyll synthesis'],
      criteriaBreakdown: [
        { criterion: 'Explanation of paleness (lack of chlorophyll)', marks: 1, maxMarks: 1 },
        { criterion: 'Explanation of stem elongation (etiolation/auxin)', marks: 1, maxMarks: 1 },
      ],
      answerRegion: {
        page: 4,
        topPercent: 16,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 18,
        label: 'Q11 (a)',
      },
    },
    {
      id: 'q11b',
      number: '11 (b)',
      mainNumber: '11',
      subPart: 'b',
      text: 'Suggest one practical measure to help Plant B recover.',
      maxMarks: 3,
      marksAwarded: 1,
      status: 'partial',
      section: 'Section C',
      questionType: 'short',
      aiFeedback: 'Partially correct. Moving plant to adequate sunlight was suggested, but acclimatization steps (gradual exposure to prevent solarization) and nutrient watering were omitted.',
      suggestedSolution: 'Transfer Plant B gradually into bright, indirect sunlight and supply balanced nitrate fertilizers to promote fresh green leaf regrowth.',
      studentAnswerText: 'Q11 (b). Move Plant B into direct sunlight so it can photosynthesize again.',
      orderInAnswerSheet: 11,
      isOutOfOrder: false,
      keyConcepts: ['Sunlight exposure', 'Acclimatization', 'Chlorophyll recovery'],
      criteriaBreakdown: [
        { criterion: 'Moving to light source', marks: 1, maxMarks: 1 },
        { criterion: 'Recovery care / watering & fertilizer details', marks: 0, maxMarks: 2 },
      ],
      answerRegion: {
        page: 4,
        topPercent: 36,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 14,
        label: 'Q11 (b)',
      },
    },
    {
      id: 'q12',
      number: '12',
      mainNumber: '12',
      text: 'A student inhales 500 mL of air per breath (Tidal Volume) at a respiratory rate of 12 breaths/minute. Calculate the total pulmonary ventilation rate in liters per minute.',
      maxMarks: 2,
      marksAwarded: 2,
      status: 'answered',
      section: 'Section C',
      questionType: 'numerical',
      aiFeedback: 'Calculation is 100% correct! (0.5 L * 12 = 6.0 L/min). Correct units supplied.',
      suggestedSolution: 'Ventilation Rate = Tidal Volume * Respiratory Rate = 0.50 L * 12 = 6.0 L/min.',
      studentAnswerText: 'Q12. Total pulmonary ventilation rate = TV * RR = 0.5 L * 12 breaths/min = 6.0 Liters/min.',
      orderInAnswerSheet: 12,
      isOutOfOrder: false,
      keyConcepts: ['Tidal Volume', 'Respiratory Rate', '6.0 L/min'],
      criteriaBreakdown: [
        { criterion: 'Formula application', marks: 1, maxMarks: 1 },
        { criterion: 'Correct value with units', marks: 1, maxMarks: 1 },
      ],
      answerRegion: {
        page: 4,
        topPercent: 52,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 14,
        label: 'Q12',
      },
    },
    {
      id: 'q13',
      number: '13',
      mainNumber: '13',
      text: 'If 150 mL of each breath stays in anatomical dead space, calculate the alveolar ventilation rate.',
      maxMarks: 3,
      marksAwarded: 3,
      status: 'answered',
      section: 'Section C',
      questionType: 'numerical',
      aiFeedback: 'Superb! Alveolar ventilation rate accurately calculated as (500 - 150) * 12 = 4200 mL/min = 4.2 L/min.',
      suggestedSolution: 'Alveolar ventilation = (Tidal Volume - Dead Space) * Respiratory Rate = (0.50 L - 0.15 L) * 12 = 4.2 L/min.',
      studentAnswerText: 'Q13. Alveolar ventilation = (TV - Dead space) * RR = (0.50 L - 0.15 L) * 12 = 0.35 * 12 = 4.2 L/min.',
      orderInAnswerSheet: 13,
      isOutOfOrder: false,
      keyConcepts: ['Dead space', 'Alveolar ventilation', '4.2 L/min'],
      criteriaBreakdown: [
        { criterion: 'Dead space subtraction', marks: 1, maxMarks: 1 },
        { criterion: 'Multiplication by breathing rate', marks: 1, maxMarks: 1 },
        { criterion: 'Unit conversion to L/min', marks: 1, maxMarks: 1 },
      ],
      answerRegion: {
        page: 4,
        topPercent: 68,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 12,
        label: 'Q13',
      },
    },
  ],
};

export const sampleMathematicsAssessment: AssessmentData = {
  id: 'maths-term-10',
  title: 'Class 10 Mathematics Assessment',
  subject: 'Mathematics',
  grade: 'Class 10th - Section A',
  studentName: 'Priya Patel',
  rollNumber: 'DPS-10A-18',
  school: 'Delhi Public School, R.K. Puram',
  date: 'August 22, 2026',
  totalMarksAwarded: 44,
  maxTotalMarks: 50,
  ocrResult: sampleMathsOcrResult,
  questionPaperFile: {
    name: 'Class_10_maths_unit_test.pdf',
    size: '2MB',
    pages: 2,
  },
  answerSheetFile: {
    name: 'student_1_answer_sheet.pdf',
    size: '8MB',
    pages: 3,
  },
  pages: [
    { pageNumber: 1, title: 'Page 1 - Quadratic Equations & Arithmetic Progressions' },
    { pageNumber: 2, title: 'Page 2 - Trigonometric Identities & Heights' },
    { pageNumber: 3, title: 'Page 3 - Coordinate Geometry & Circle Theorems' },
  ],
  unmatchedAnswers: [],
  questions: [
    {
      id: 'm1',
      number: '1',
      mainNumber: '1',
      text: 'Find the roots of the quadratic equation 2x² - 7x + 3 = 0 using the quadratic formula.',
      maxMarks: 3,
      marksAwarded: 3,
      status: 'answered',
      section: 'Section A',
      questionType: 'numerical',
      aiFeedback: 'Accurate step-by-step factorization with correct roots x = 3 and x = 1/2.',
      suggestedSolution: 'D = b² - 4ac = 49 - 24 = 25. x = (7 ± 5)/4 => x = 3, 1/2.',
      studentAnswerText: 'Q1. 2x² - 6x - x + 3 = 0 => 2x(x-3) - 1(x-3) = 0 => (2x-1)(x-3)=0 => x = 3, 1/2.',
      orderInAnswerSheet: 1,
      isOutOfOrder: false,
      keyConcepts: ['Quadratic Formula', 'Roots x = 3, 1/2'],
      answerRegion: {
        page: 1,
        topPercent: 8,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 25,
        label: 'Q1',
      },
    },
    {
      id: 'm2',
      number: '2',
      mainNumber: '2',
      text: 'Find the 20th term from the last term of the AP: 3, 8, 13, ..., 253.',
      maxMarks: 4,
      marksAwarded: 4,
      status: 'answered',
      section: 'Section A',
      questionType: 'numerical',
      aiFeedback: 'Excellent! Reversed the series with d = -5 and found a20 = 158 without calculation errors.',
      suggestedSolution: 'Reverse AP: 253, 248, ..., 3. a = 253, d = -5. a20 = 253 + 19(-5) = 253 - 95 = 158.',
      studentAnswerText: 'Q2. Reverse AP: a = 253, d = -5. a20 = a + 19d = 253 + 19(-5) = 253 - 95 = 158.',
      orderInAnswerSheet: 2,
      isOutOfOrder: false,
      keyConcepts: ['Arithmetic Progression', 'Reverse nth term', 'a20 = 158'],
      answerRegion: {
        page: 1,
        topPercent: 36,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 28,
        label: 'Q2',
      },
    },
    {
      id: 'm3',
      number: '3',
      mainNumber: '3',
      text: 'Prove that: (sin θ / (1 + cos θ)) + ((1 + cos θ) / sin θ) = 2 cosec θ.',
      maxMarks: 4,
      marksAwarded: 4,
      status: 'answered',
      section: 'Section B',
      questionType: 'long',
      aiFeedback: 'Flawless trigonometric proof applying sin²θ + cos²θ = 1 and reducing to 2 / sin θ = 2 cosec θ.',
      suggestedSolution: 'LHS = (sin²θ + (1+cosθ)²)/(sinθ(1+cosθ)) = (sin²θ + 1 + 2cosθ + cos²θ)/(sinθ(1+cosθ)) = (2 + 2cosθ)/(sinθ(1+cosθ)) = 2/sinθ = 2 cosecθ = RHS.',
      studentAnswerText: 'Q3. LHS = [sin²θ + (1+cosθ)²]/[sinθ(1+cosθ)] = [1 + 1 + 2cosθ]/[sinθ(1+cosθ)] = 2(1+cosθ)/[sinθ(1+cosθ)] = 2/sinθ = 2cosecθ = RHS.',
      orderInAnswerSheet: 3,
      isOutOfOrder: false,
      keyConcepts: ['Trig identity', 'sin²θ + cos²θ = 1', 'LHS = RHS'],
      answerRegion: {
        page: 2,
        topPercent: 8,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 32,
        label: 'Q3',
      },
    },
    {
      id: 'm4',
      number: '4',
      mainNumber: '4',
      text: 'Find the coordinates of a point A, where AB is the diameter of a circle whose centre is (2, -3) and B is (1, 4).',
      maxMarks: 4,
      marksAwarded: 4,
      status: 'answered',
      section: 'Section C',
      questionType: 'numerical',
      aiFeedback: 'Excellent application of midpoint formula. Obtained A(x, y) = (3, -10).',
      suggestedSolution: 'Midpoint of AB = C(2, -3). (x + 1)/2 = 2 => x = 3; (y + 4)/2 = -3 => y = -10. Point A is (3, -10).',
      studentAnswerText: 'Q4. Let A=(x,y). Center (2,-3) is midpoint of AB. (x+1)/2 = 2 => x=3. (y+4)/2 = -3 => y=-10. A = (3,-10).',
      orderInAnswerSheet: 4,
      isOutOfOrder: false,
      keyConcepts: ['Midpoint formula', 'Coordinate circles'],
      answerRegion: {
        page: 3,
        topPercent: 8,
        leftPercent: 12,
        widthPercent: 82,
        heightPercent: 30,
        label: 'Q4',
      },
    },
    {
      id: 'm5',
      number: '5',
      mainNumber: '5',
      text: 'Find the area of a triangle whose vertices are A(1, -1), B(-4, 6), and C(-3, -5).',
      maxMarks: 5,
      marksAwarded: 0,
      status: 'unanswered',
      section: 'Section C',
      questionType: 'numerical',
      aiFeedback: 'Question unattempted by student. Formula: Area = 1/2 |x1(y2-y3) + x2(y3-y1) + x3(y1-y2)| = 1/2 |1(11) - 4(-4) - 3(-7)| = 1/2 |11 + 16 + 21| = 24 sq units.',
      suggestedSolution: 'Area = 24 square units.',
      orderInAnswerSheet: undefined,
      isOutOfOrder: false,
      keyConcepts: ['Area of triangle coordinate formula'],
    },
  ],
};
